#!/bin/sh


# Copyright (c) 2014 Jason Masker <jason@masker.net>
# All rights reserved.

# This file is part of wordMerge.

# wordMerge is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# wordMerge is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with wordMerge.  If not, see <http://www.gnu.org/licenses/>.


exit `osascript <<EOS

set o to "$1"
set a to "$2"
set b to "$3"
set o to POSIX file o
set a to POSIX file a
set b to POSIX file b

tell application "Finder" to set oname to (name of (info for o))
tell application "Finder" to set aname to (name of (info for a))

tell application "Microsoft Word"
	activate
	close documents saving yes
	open file name o
	merge document oname file name a
	close document oname saving no
	save as document 1 file name a file format format template
	merge document aname file name b
	close document aname saving no
	save as document 1 file name a file format format template
end tell

set question to display dialog "Merge successful?" buttons {"Yes", "No"} default button 2
set answer to button returned of question

tell application "Microsoft Word"
	save as document aname file name a file format format template
	close document aname
end tell

if answer is equal to "Yes" then
	return 0
else
	return 1
end if

EOS
`


